### PR TITLE
Sweep from branch

### PR DESCRIPTION
**Pull request by ANUSHMANGAL01**

### CODE REVIEW

**Comment by SachinSahu431** [comment]
Is there any code written which prints the complete minefield and also accepts coordinates from the user??

**Comment by ANUSHMANGAL01** [comment]
> Is there any code written which prints the complete minefield and also accepts coordinates from the user??

I don't think so... That will be done in the main class

**Comment by MathewKJ2048** [comment]
printing the Minefield and accepting user input will be carried out by main()
There is an accessor char get_state_of(int,int) which returns the required character to the calling function to print it

**Comment by MathewKJ2048** [comment]
The function looks good. Has it been tested? If so, I can merge.

**Comment by MathewKJ2048** [comment]
I put sweep_util() under private for security reasons and created a new sub-branch to your pull request. Please merge the sub-branch if you are ok with the change.

By security reasons, I mean that calling functions should not be able to access sweep_util() because that will give them too much control over the Minefield object

**Comment by SachinSahu431** [comment]
> The function looks good. Has it been tested? If so, I can merge.

Be careful while merging, class and legend are not updated in this branch...

**Comment by ANUSHMANGAL01** [comment]
> The function looks good. Has it been tested? If so, I can merge.

Yes please.. You can merge

**Comment by MathewKJ2048** [comment]
Ok. Il copy and paste instead of merging. That way no conflicts will arise

**Review by SachinSahu431 — APPROVED** [review]

**Comment by MathewKJ2048** [comment]
I have added your functions to the modified version of Minefield. So Im closing this pull request instead of committing it to main since main is itself outdated

**Pull request closed without merging**
