### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MathewKJ2048**

### CODE REVIEW

**Comment by MathewKJ2048** [comment]
I added the vocabulary we agreed on to the Readme file

**Comment by JSRam03** [comment]
No issues u r just including the vocabulary ryt

**Comment by SachinSahu431** [comment]
Looks good. Go ahead!

**Comment by MathewKJ2048** [comment]
2 more assents needed

**Review by SachinSahu431 — APPROVED** [review]

**Comment by ANUSHMANGAL01** [comment]
It's fine.

**Pull request merged**
